Repository TayMcKenzieNZ/rpemotes, pull requests merged in 2023-01, with the labels that each got.

#102 Ability to Toggle Favorite Emote
  client/Emote.lua
  client/EmoteMenu.lua
Labels: Enhancement 💡

#101 Feat: Add Exit Emotes
  client/AnimationList.lua
  client/AnimationListCustom.lua
  client/Emote.lua
Labels: Enhancement 💡

#114 feat: add crawling
  client/Crouch.lua
  client/Emote.lua
  config.lua
Labels: Enhancement 💡, Help Wanted

#119 refactor: separate out pointing
  client/Emote.lua
  client/Pointing.lua
  config.lua
  fxmanifest.lua
Labels: Enhancement 💡

#121 Fix for MenuKeybindEnabled
  client/Emote.lua
Labels: Help Wanted

#140 [test] feat: toggle between moving emotes and not
  NativeUI.lua
  Translations.lua
  client/AnimationList.lua
  client/Emote.lua
Labels: Enhancement 💡
